import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { ComponentProps } from 'react';
import { OpaqueColorValue, type StyleProp, type TextStyle } from 'react-native';

export const ICON_NAMES = {
  house: 'home',
  person: 'person',
  heart: 'favorite',
  clipboard: 'assignment',
  document: 'description',
  bell: 'notifications',
  'chart-bar': 'bar-chart',
  star: 'star',
  checkmark: 'check-circle',
  clock: 'schedule',
  warning: 'warning',
  info: 'info',
  'plus-circle': 'add-circle',
  gear: 'settings',
  help: 'help',
  'menu-book': 'menu-book',
  'local-hospital': 'local-hospital',
  'medical-services': 'medical-services',
  'monitor-heart': 'monitor-heart',
  accessibility: 'accessibility',
  school: 'school',
  'trending-up': 'trending-up',
  'trending-down': 'trending-down',
  'arrow-forward': 'arrow-forward',
  'arrow-back': 'arrow-back',
  close: 'close',
  menu: 'menu',
  search: 'search',
  'filter-list': 'filter-list',
  'grid-view': 'grid-view',
  list: 'list',
  calendar: 'calendar-today',
  timelapse: 'timelapse',
  group: 'group',
  people: 'people',
  phone: 'phone',
  mail: 'email',
  lock: 'lock',
  visibility: 'visibility',
  'visibility-off': 'visibility-off',
  delete: 'delete',
  edit: 'edit',
  share: 'share',
  download: 'download',
  cloud: 'cloud',
  'cloud-done': 'cloud-done',
  wifi: 'wifi',
  'battery-full': 'battery-full',
  thermostat: 'thermostat',
  air: 'air',
  'water-drop': 'water-drop',
  'favorite-border': 'favorite-border',
  psychology: 'psychology',
  medication: 'medication',
  hotel: 'hotel',
  'medical-information': 'medical-information',
  'line-weight': 'line-weight',
  'insert-drive-file': 'insert-drive-file',
  folder: 'folder',
  flag: 'flag',
  'track-changes': 'track-changes',
  lightbulb: 'lightbulb',
  'auto-awesome': 'auto-awesome',
  'smart-toy': 'smart-toy',
  'fitness-center': 'fitness-center',
  'directions-walk': 'directions-walk',
} as const;

export type IoniconName = keyof typeof ICON_NAMES;
export type MaterialIconName = ComponentProps<typeof MaterialIcons>['name'];

export function IconSymbol({
  name,
  size = 24,
  color,
  style,
}: {
  name: IoniconName;
  size?: number;
  color: string | OpaqueColorValue;
  style?: StyleProp<TextStyle>;
}) {
  return <MaterialIcons color={color} size={size} name={ION_ICONS[name] as MaterialIconName} style={style} />;
}

const ION_ICONS: Record<string, string> = {
  house: 'home',
  person: 'person',
  heart: 'favorite',
  clipboard: 'assignment',
  document: 'description',
  bell: 'notifications',
  'chart-bar': 'bar-chart',
  star: 'star',
  checkmark: 'check-circle',
  clock: 'schedule',
  warning: 'warning',
  info: 'info',
  'plus-circle': 'add-circle',
  gear: 'settings',
  help: 'help',
  'menu-book': 'menu-book',
  'local-hospital': 'local-hospital',
  'medical-services': 'medical-services',
  'monitor-heart': 'monitor-heart',
  accessibility: 'accessibility',
  school: 'school',
  'trending-up': 'trending-up',
  'trending-down': 'trending-down',
  'arrow-forward': 'arrow-forward',
  'arrow-back': 'arrow-back',
  close: 'close',
  menu: 'menu',
  search: 'search',
  'filter-list': 'filter-list',
  'grid-view': 'grid-view',
  list: 'list',
  calendar: 'calendar-today',
  timelapse: 'timelapse',
  group: 'group',
  people: 'people',
  phone: 'phone',
  mail: 'email',
  lock: 'lock',
  visibility: 'visibility',
  'visibility-off': 'visibility-off',
  delete: 'delete',
  edit: 'edit',
  share: 'share',
  download: 'download',
  cloud: 'cloud',
  'cloud-done': 'cloud-done',
  wifi: 'wifi',
  'battery-full': 'battery-full',
  thermostat: 'thermostat',
  air: 'air',
  'water-drop': 'water-drop',
  'favorite-border': 'favorite-border',
  psychology: 'psychology',
  medication: 'medication',
  hotel: 'hotel',
  'medical-information': 'medical-information',
  'line-weight': 'line-weight',
  'insert-drive-file': 'insert-drive-file',
  folder: 'folder',
  flag: 'flag',
  'track-changes': 'track-changes',
  lightbulb: 'lightbulb',
  'auto-awesome': 'auto-awesome',
  'smart-toy': 'smart-toy',
  'fitness-center': 'fitness-center',
  'directions-walk': 'directions-walk',
};